### ISSUE TITLE
server starting on 127.0.0.1 and cant be accesssed from www

### ISSUE THREAD

**Issue by zingabuka** [erindru/m2t#1]
when i start the ./start.py it gets started on the 127.0.0.1 instead of 0.0.0.0

so it can accessed only by localhost, how can i make it be accesible from world ?

**Comment by zingabuka** [comment]
you need to specify the host while starting the cherrypy

you can do that by modifiying 2 files

edit config.py

add this in the end
bottle_host = '0.0.0.0'

#####################################################
modify start.py

and replace 
run(port=config.bottle_port, debug=config.bottle_debug, reloader=config.bottle_reload, server=config.bottle_server)

with this

run(host=config.bottle_host ,port=config.bottle_port, debug=config.bottle_debug, reloader=config.bottle_reload, server=config.bottle_server)

**Comment by erindru** [comment]
FYI the intended configuration is to proxy to it via a proper webserver, such as nginx or apache. If you want to run it directly however, that's cool, and you already figured out how :)
