### ISSUE TITLE
URL vhost issue

### ISSUE THREAD

**Issue by vidplace7** [erindru/m2t#4]
http://m2t.openseedbox.com/, which you link in the README links to a Karate Club website ;) thought you should know.

In other news, thanks for all your work on openseedbox, I've been messing around with it for a while and making some local changes :)

**Comment by erindru** [comment]
That's right, I was getting hammered by someone downloading russian torrents so I disabled it. I have removed it from the README

Glad you like Openseedbox - I have started rewriting it in PHP as theres several things I dont like about the current version, but progress has been slow :)

**Comment by vidplace7** [comment]
Keep us informed on your PHP rewrite :) I'm a fledgling PHP coder myself, would love to get involved in a rewrite! Nginx + PHP5-FPM is much lighter than Java6 in my experience.
